=== xatapult/xtpxlib-xoffice/xsd/xlsx-modify.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.xtpxlib.nl/ns/xoffice"
  xmlns:xtlxo="http://www.xtpxlib.nl/ns/xoffice">
  <xs:element name="xlsx-modifications">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="worksheet">
          <xs:complexType>
            <xs:sequence>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="row">
                <xs:annotation>
                  <xs:documentation>Definition of the row for the value insertion. Either @name or @index must defined, not both.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="column">
                      <xs:annotation>
                        <xs:documentation>Definition of the column for the value insertion. Either @name or @index must defined, not both.</xs:documentation>
                      </xs:annotation>
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="value">
                            <xs:annotation>
                              <xs:documentation>The value to insert.</xs:documentation>
                            </xs:annotation>
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute default="detect" name="datatype" type="xtlxo:t-datatype"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attributeGroup ref="xtlxo:ag-sheet-coordinate"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attributeGroup ref="xtlxo:ag-sheet-coordinate"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required">
              <xs:annotation>
                <xs:documentation>Name of the worksheet (as displayed on the Excel tab).
</xs:documentation>
              </xs:annotation>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:anyAttribute namespace="##any" processContents="skip">
        <xs:annotation>
          <xs:documentation>Additional information may be present.</xs:documentation>
        </xs:annotation>
      </xs:anyAttribute>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="ag-sheet-coordinate">
    <xs:annotation>
      <xs:documentation>A row or column coordinate on a worksheet.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="index" type="xs:positiveInteger">
      <xs:annotation>
        <xs:documentation>The row or column index (starting with 1). Has precedence over @name.
</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="name" type="xs:string">
      <xs:annotation>
        <xs:documentation>An Excel name defined on this worksheet. The row or column of the left-upper cell is used. </xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="offset" type="xs:integer">
      <xs:annotation>
        <xs:documentation>The offset when @name is used. Ignored otherwise.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:simpleType name="t-datatype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="detect"/>
      <xs:enumeration value="string"/>
      <xs:enumeration value="numeric"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== xatapult/xtpxlib-xoffice/xplmod/excel.mod/test/test-modify-xlsx-input.xml
<xlsx-modifications xmlns="http://www.xtpxlib.nl/ns/xoffice"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.xtpxlib.nl/ns/xoffice ../../../xsd/xlsx-modify.xsd">
  
  <worksheet name="TEST">
    
    <row name="NAMEDCELL" >
      <column name="NAMEDCELL" >
        <value datatype="string">in the named cell...</value>
      </column>
    </row>
    
    <row index="1">
      <column index="1">
        <value>Upper left-hand corner</value>
      </column>
      <column index="2">
        <value datatype="numeric">6E3</value>
      </column>
    </row>
  </worksheet>
  
</xlsx-modifications>
